# Generated by Django 5.2.12 on 2026-04-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cursodisciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodisciplina',
            name='carga_horaria',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursodisciplina',
            name='periodo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
